### ISSUE TITLE
401 when Retrieving Credential 

### ISSUE THREAD

**Issue by mkkeffeler** [cyberark/ansible-conjur-collection#29]
logs from conjur

<13>1 2020-07-16T22:45:43.027+00:00 8b117ffb7cc7 nginx - - [meta sequenceId="40"] 10.202.76.252 "POST /authn/autozone/host%2Funix-awx/authenticate HTTP/1.1" 200 592 "-" "Python-urllib/3.6" 0.028 0.025
<13>1 2020-07-16T22:45:43.027+00:00 8b117ffb7cc7 nginx - - [meta sequenceId="41"] 10.202.76.252 "GET /secrets/autozone/variable/AZ%2FNonprod%2FN_A_NIX_RHLK_SPA_UNIX_NH%2FOperating+System-N_A_NIX_RHLK_NH-dv-wildcat-dx01.autozone.com-tugrnaut%2Fpassword HTTP/1.1" 401 29 "-" "Python-urllib/3.6" 0.002 0.002

login was successful, cant retrieve. here is the variable in ansible:

CONJUR_SSH_KEY: "{{ lookup('conjur_variable', 'AZ/Nonprod/N_A_NIX_RHLK_SPA_UNIX_NH/Operating System-N_A_NIX_RHLK_NH-dv-wildcat-dx01.autozone.com-tugrnaut/password') }}"

ansible error is in picture

![2020-07-16_17-50-48](https://user-images.githubusercontent.com/12587979/87730259-e33d0f80-c78c-11ea-8845-f74764b485df.png)

Ansible version info is in picture 

![MicrosoftTeams-image (11)](https://user-images.githubusercontent.com/12587979/87730301-f8b23980-c78c-11ea-9855-e480fbbe79a9.png)

**Comment by mkkeffeler** [comment]
<13>1 2020-07-16T22:56:25.772+00:00 8b117ffb7cc7 nginx - - [meta sequenceId="62"] 10.202.76.252 "POST /authn/autozone/host%2Funix-awx/authenticate HTTP/1.1" 200 592 "-" "Python-urllib/3.6" 0.022 0.020
<13>1 2020-07-16T22:56:25.772+00:00 8b117ffb7cc7 nginx - - [meta sequenceId="63"] 10.202.76.252 "GET /secrets/autozone/variable/platformopstest HTTP/1.1" 401 29 "-" "Python-urllib/3.6" 0.002 0.002

**Comment by mkkeffeler** [comment]
we downgraded ansible versiions and this became not an issue with normal variables (variablles with a space still dont work on the older version though)

<13>1 2020-07-16T23:00:38.066+00:00 8b117ffb7cc7 nginx - - [meta sequenceId="23"] 10.202.76.252 "POST /authn/autozone/host%2Funix-awx/authenticate HTTP/1.1" 200 592 "-" "Python-urllib/2.7" 0.025 0.020
<13>1 2020-07-16T23:00:38.066+00:00 8b117ffb7cc7 nginx - - [meta sequenceId="24"] 10.202.76.252 "GET /secrets/autozone/variable/platformopstest HTTP/1.1" 200 43 "-" "Python-urllib/2.7" 0.015 0.014


same lookup variable as above comment, example of retrieving the secret data in a debug task in ansible
![MicrosoftTeams-image (12)](https://user-images.githubusercontent.com/12587979/87730806-7296f280-c78e-11ea-878d-cf26ee2d4dd8.png)


ansible version information
![MicrosoftTeams-image (13)](https://user-images.githubusercontent.com/12587979/87730829-82aed200-c78e-11ea-940b-479dd638a934.png)

**Comment by mkkeffeler** [comment]
our playbook is setting a host variable CONJUR_SSH_KEY= the lookup of conjur_variable, and we are trying to reference it like this 

```
- hosts: localhost
  tasks:
    - debug:
        msg: "{{hostvars['dv-server1'].CONJUR_SSH_KEY}}"
    - debug:
        msg: "{{hostvars}}"
- name: include next playbook
  import_playbook: playbook.yml
```

**Comment by sgnn7** [comment]
Hey @mkkeffeler - sorry to hear that you have a problem with this! 

Since it is after-hours, we will triage this sometime tomorrow (CC: @cyberark / community-and-integrations-team / @izgeri / @AndrewCopeland). One big things to keep in mind is that [the conjur plugin for AWX](https://github.com/ansible/awx/blob/5fcf1a2d5ef28344fd2e252c66bf92cd40440e17/awx/main/credential_plugins/conjur.py) is **_not_** this repo's plugin that's [published to Ansible Galaxy](https://galaxy.ansible.com/cyberark/conjur) so this may not be the correct repository for filing this issue. 

In the meantime, can you provide us with the following information so that we can start tomorrow on it:
- What version of AWX was this problem encountered with?
- What version of Conjur/DAP are you fetching secrets from?
- Did this work previously?
  - If it worked previously, can you provide us with the working and non-working version numbers?
  - If it worked previously can you provide us with the working debug log of the same secret fetch?
- Can you also provide us with:
  - Snippet of the sample policy where this variable is defined (with sensitive data redacted)
  - Output of `conjur list` that shows this variable

As a side-note, I do see that there was a change in the AWS conjur plugin with [this](https://github.com/ansible/awx/commit/cfe8a1722c1aeb70c5b26a939672d6975e880de2#diff-78078ab1a37868cfd5eada2c57843c8f) and [this](https://github.com/ansible/awx/commit/4531c418e26f9b47fc1224d96b202b89c159132e#diff-78078ab1a37868cfd5eada2c57843c8f) commit recently so it's possible that this is fixed already in AWX but I don't know enough about this project to give you clear guidance on that yet. With that said, we will update you once we look into it with team members that work on the AWX plugin.

Thanks,
Srdjan

**Comment by sgnn7** [comment]
PS: this comment may be relevant: https://github.com/ansible/awx/issues/7191#issuecomment-644704726

**Comment by mkkeffeler** [comment]
Well we completely ruled out spaces being an issue with the follow up test. The failed test was on AWX 12.0.0, but this seems irrelevant as the Conjur piece of this comes in at the ansible level with the lookup component. 

I provided above a working example of retrieving the credential in an older version of ansible, then we upgraded it (and AWX), and saw the same playbook
Now failing

**Comment by mkkeffeler** [comment]
We are running Conjur 11.3

**Comment by sgnn7** [comment]
> I provided above a working example of retrieving the credential in an older version of ansible, then we upgraded it (and AWX), and saw the same playbook now failing

Ah sorry, I missed that there was an example working there!

So I have a slight idea of what's going on here (bad secret's path slash encoding) but I will defer the answer to someone more knowledgable in the different lookup modules that conjur provides for Ansible since my personal expertise is only in this specific Ansible Galaxy module.

**Comment by mkkeffeler** [comment]
Sure, and just to further clarify I’d say to please see my example above successfully retrieving a secret in the older version of ansible with a secret that has no slashes or spaces, and then taking that same playbook to the same version that broke with a credential that DID have slashes, and it still returned 401. So i believe we ruled out it being an issue with slashes or spaces, by that test.

Will see what others have to say :)

**Comment by mkkeffeler** [comment]
Exact invokement of the plugin was like this:

setting a var: CONJUR_SSH_KEY: "{{ lookup('conjur_variable', 'AZ/Nonprod/N_A_NIX_RHLK_SPA_UNIX_NH/Operating System-N_A_NIX_RHLK_NH-dv-wildcat-dx01.autozone.com-tugrnaut/password') }}"


as a note, we did end up downloading the galaxy collection https://galaxy.ansible.com/cyberark/conjur and then changing above to 

CONJUR_SSH_KEY: "{{ lookup('cyberark.conjur.conjur_variable', 'AZ/Nonprod/N_A_NIX_RHLK_SPA_UNIX_NH/Operating System-N_A_NIX_RHLK_NH-dv-wildcat-dx01.autozone.com-tugrnaut/password') }}"


and it worked, so seems like something is just up with the versiion included in ansible

**Comment by izgeri** [comment]
@mkkeffeler thanks for verifying. This collection (which is published to Galaxy as `cyberark.conjur`) has the fix for variables with spaces. Ansible 2.10 will refer to this collection instead of the old lookup plugin that was part of core; that lookup plugin will be deprecated.

I would strongly recommend using the lookup plugin that is part of this collection in your pipelines, as this is the version that we will be maintaining and applying bug fixes to as needed going forward. If for some reason this doesn't work for your use case, please let us know and I'll see if we can work with Ansible to explore other options.

**Comment by izgeri** [comment]
Since we have a version that fixes this error available in the Galaxy collection, I'll be closing this issue now. If you continue to experience issues or have any further questions, please feel free to reopen this issue or contact us on [Discourse](https://discuss.cyberarkcommons.org).
