### ISSUE TITLE
ansible-conjur-host-identity docs are migrated 

### ISSUE THREAD

**Issue by BradleyBoutcher** [cyberark/ansible-conjur-collection#36]
The docs for https://github.com/cyberark/ansible-conjur-host-identity have been migrated, pending the migration of the project and tests themselves to this collection.

AC:
- [ ] Migrate the docs for the role to the collection, and revise to be based on how the role works within the collection
- [ ] Update the Conjur docs card [cyberark/conjur-docs#895](https://github.com/cyberark/conjur-docs/issues/895) to include what the docs should say now 
  - @izgeri's [gist from the last update](https://gist.github.com/izgeri/341c4736f540ed75bc0c0adb3a050bdb) might be a useful baseline, and there are also some Word docs linked in the docs issue that may help

**Comment by izgeri** [comment]
Note: cyberark/conjur-docs#895 has been migrated to cyberark/conjur-docs#1015

I don't know if anyone has written good docs yet on best practices for collection usage, and the README in this repo also looks a little sparse. It might be good to write up a gist for what you think the online docs should have, given that:
- Ansible 2.9 and earlier have a built-in lookup plugin (though it isn't being maintained, and our collection will be)
- Ansible 2.10 will have a reference to our collection lookup plugin built-in
- There is also a built-in lookup plugin in Ansible Tower / AWX

I think in all cases, I'd like to recommend people invoke the collection lookup plugin specifically, since that is our official lookup plugin that we maintain / test / etc.

It is ok if the README here remains sparse, and we link people to the Conjur docs. Or we could really populate this README with detailed instructions, and have an overview in the docs that links to GitHub. I leave it to you and @suefran to figure out - I will be happy if the end result is more comprehensive, clear guidelines for using our Ansible tools.

**Comment by izgeri** [comment]
Closing, as we have done as much of this as we can at this point.
